apiVersion: apps/v1
kind: Deployment
metadata:
  name: restfulapideployment
  labels:
    app: restful-api
spec:
  replicas: 1
  selector:
    matchLabels:
       app: restful-api-label    
  template:
    metadata:
      labels:
        app: restful-api-label     
    spec:
      containers:
      - name: restful-api-latest
        image: dockersid1988/restful-api2:latest
        ports:
        - containerPort: 8000
          name: http